version: '3'

services:
  nerdiqtestserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app"
  nerdiqtestclient:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - "./client:/app"
